# Generated by Django 4.2.2 on 2023-06-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(choices=[], max_length=5),
        ),
    ]
