# Generated by Django 4.2.2 on 2023-06-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_bloodbank_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbank',
            old_name='bag_quentity',
            new_name='bag_quantity',
        ),
    ]
