# Generated by Django 4.2.2 on 2023-06-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_bloodbank_donor_donor_bloodbank_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='bag_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
